Добавлены решения для раздела примитивные типы данных
js-tasks-ru/js-20210126_dementiy pull request #2
Opened 2021-01-31 17:48 UTC by Dementiy

2021-01-31 17:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-02-01 09:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let sortedArray = [...arr].sort((a, b) => a.localeCompare(b, ["ru", "en"], {caseFirst: "upper"}));
помните на занятии мы обсуждали использование `const` и `let`?
`sortedArray` - это значение переменной которое мы не будем переприсваивать, поэтому следует воспользоваться `const`

2021-02-01 09:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return param == "asc" ? sortedArray : sortedArray.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-02-01 09:25 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let new_obj = {};
Пожалуйста не используйте "snake_case" нотацию. При разработке на JS принято использовать "camelCase"

2021-02-01 09:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let new_obj = {};
подумайте, может данную переменную следует объявить через `const`?

2021-02-01 09:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (!fields.includes(field)) {
использование `includes` - good 👍

2021-02-01 09:27 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let field in obj) {
для итерации по объекту редко используется цикл `for...in`, кстати `field` в данном цикле это тоже `const`

2021-02-01 09:28 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let new_obj = {};
смотрите замечания в `omit`

2021-02-01 09:29 UTC, dosandk requested changes
необходимо исправить решение `sortString` и разобраться с нотацией для именования, а также с иcпользованием `let` и `const`

2021-02-01 11:51 UTC, Dementiy commented on 02-javascript-data-types/3-omit/index.js
> +    for (let field in obj) {
Не совсем понял про `for...in`, я же таким циклом по свойствам объекта итерируюсь. `let` на `const` исправил.

2021-02-02 11:57 UTC, dosandk approved these changes
good 👍

2021-02-02 11:57 UTC, merged